language: bash

services:
- docker

script:

  # Build all images
  - docker build --build-arg PLATFORM=linux-amd64 -t acrelle/iozone:linux-amd64 -f Dockerfile .
  - docker build --build-arg PLATFORM=linux-arm -t acrelle/iozone:linux-arm -f Dockerfile.linux-armhf .

  - >

    if [ "$TRAVIS_BRANCH" == "master" ]; then
      # Push all images
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker push acrelle/iozone:linux-amd64
      docker push acrelle/iozone:linux-arm

      # Download manifest-tool
      wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
      mv manifest-tool-linux-amd64 manifest-tool
      chmod +x manifest-tool

      # Push manifest-list
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "acrelle/iozone:OS-ARCH" --target "acrelle/iozone:$TRAVIS_BUILD_NUMBER"
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "acrelle/iozone:OS-ARCH" --target "acrelle/iozone:latest"

      # Update microbadger badge
      curl -X POST "$MICROBADGER_URL"
    fi